# Generated by Django 2.2.3 on 2019-07-25 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('uploaddata', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_id', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
    ]
