# Generated by Django 2.2.3 on 2019-07-25 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Service')),
                ('descrption', models.CharField(max_length=500)),
                ('uploaddata', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
