# Generated by Django 2.2.3 on 2019-08-01 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('description', models.TextField(max_length=10000)),
                ('price', models.DecimalField(decimal_places=3, max_digits=1000)),
                ('timecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('featured', models.BooleanField()),
            ],
        ),
    ]
